# AWS credentials and region information
production:
  AWS_ACCESS_KEY_ID: access_key_id_goes_here
  AWS_SECRET_ACCESS_KEY: access_key_goes_here
  AWS_REGION: aws_region_goes_here
  VAULT_BUCKET_NAME: keyshare_vault_name_goes_here
  KEYSHARE_MASTER_KEY: super_secret_master_password
test:
  AWS_ACCESS_KEY_ID: access_key_id_goes_here
  AWS_SECRET_ACCESS_KEY: access_key_goes_here
  AWS_REGION: aws_region_goes_here
  KEYSHARE_MASTER_KEY: super_secret_master_password
  # No vault bucket name variable needed for testing env as it is randomly generated each run
